version: '3.7'

# https://start.1password.com/open/i?a=SQMVORNVPRBJFOXHVQXATLEU24&v=7nuj5jugclm3ixkn2fbwmufkeu&i=6ngbn6kbzmpifw237nd6gadteu&h=my.1password.com
services:
    server-asset-sg:
        container_name: server-asset-sg
        image: server-asset-sg:latest
        environment:
            PORT: 3333
            DATABASE_URL:
            ELASTICSEARCH_URL: https://elastic.lambda-it.ch
            ELASTICSEARCH_USERNAME:
            ELASTICSEARCH_PASSWORD:
        ports:
            - 3333:3333
