version: '3.7'

services:
    db:
        container_name: asset-swissgeol-postgres
        image: registry.lambda-it.ch/lambda/postgis-gotrue
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - ./volumes/db/init:/docker-entrypoint-initdb.d

        # volumes:
        #     - ./volumes/pgadmin/config:/pgadmin4/config

    pgadmin:
        container_name: asset-swissgeol-pgadmin
        image: dpage/pgadmin4
        ports:
            - 5051:5050
        depends_on:
            - db
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres@lambda-it.ch
            - PGADMIN_DEFAULT_PASSWORD=postgres
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_SERVER_JSON_FILE=/pgadmin4/config/servers.json
        volumes:
            - ./volumes/pgadmin/config:/pgadmin4/config
            - ./volumes/pgadmin/data:/pgadmin4/data

    gdal:
        container_name: asset-swissgeol-gdal
        image: osgeo/gdal:ubuntu-full-latest
        volumes:
            - ./volumes/gdal:/home
        command: tail -f /dev/null

    elasticsearch:
        container_name: asset-swissgeol-elasticsearch
        image: elasticsearch:8.4.3
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            # IMPORTANT: do not disable xpack.security for staging or production
            - xpack.security.enabled=false
            - discovery.type=single-node
        volumes:
            - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        container_name: asset-swissgeol-kibana
        image: kibana:8.4.3
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    auth:
        container_name: asset-swissgeol-auth
        image: supabase/gotrue@sha256:794d7df376329df93c0d9ed9237868363de5c858301147e08e6620fb67d1a2c6
        depends_on:
            - db
        restart: unless-stopped
        ports:
            - 8866:9999
        environment:
            GOTRUE_API_HOST: 0.0.0.0
            PORT: 9999
            GOTRUE_SITE_URL: 'http://localhost:4200'
            GOTRUE_JWT_SECRET: 'your-super-secret-jwt-token-with-at-least-32-characters-long'
            GOTRUE_COOKIE_KEY: asset-sg
            GOTRUE_DB_DRIVER: postgres
            DB_NAMESPACE: auth
            DATABASE_URL: postgres://swissgeol_asset:swissgeol_asset@db:5432/postgres?search_path=auth
            GOTRUE_DISABLE_SIGNUP: false
            GOTRUE_SMTP_ADMIN_EMAIL: info@digital-factory-bern.ch
            GOTRUE_SMTP_HOST: smtp.swizzonic-mail.ch
            GOTRUE_SMTP_PORT: 465
            GOTRUE_SMTP_USER: 
            GOTRUE_SMTP_PASS: 
            GOTRUE_SMTP_SENDER_NAME: asset-swissgeol
            GOTRUE_MAILER_URLPATHS_INVITE: http://localhost:4200/auth/verify
            GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_RECOVERY: http://localhost:4200/auth/verify
            GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
            GOTRUE_MAILER_SUBJECTS_INVITE: '{{if eq .Data.lang "de"}} Einladung für asset.swissgeol.ch Login {{else if eq .Data.lang "fr"}} Invitation à se connecter à asset.swissgeol.ch {{else if eq .Data.lang "it"}} Invito all''accesso a asset.swissgeol.ch {{else if eq .Data.lang "rm"}} RM TODO TRANSLATE Einladung für asset.swissgeol.ch Login {{else}} Invitation to asset.swissgeol.ch {{end}}'
            GOTRUE_MAILER_TEMPLATES_INVITE: http://localhost:4200/assets/email-templates/invite.html
            GOTRUE_MAILER_SUBJECTS_RECOVERY: '{{if eq .Data.lang "de"}} Passwort zurücksetzen für asset.swissgeol.ch {{else if eq .Data.lang "fr"}} Réinitialiser le mot de passe pour asset.swissgeol.ch {{else if eq .Data.lang "it"}} Reimpostare la password di asset.swissgeol.ch {{else if eq .Data.lang "rm"}} RM TODO TRANSLATE Passwort zurücksetzen für asset.swissgeol.ch {{else}} Password reset for asset.swissgeol.ch {{end}}'
            GOTRUE_MAILER_TEMPLATES_RECOVERY: http://localhost:4200/assets/email-templates/recover.html

    ocr:
        container_name: asset-swissgeol-ocr
        image: 'registry.lambda-it.ch/swissgeol/ocr'
        ports:
            - '5000:5000'
        environment:
            - OCR_CPUS=2
            - OPTIMIZE_LEVEL=0
            - OMP_THREAD_LIMIT=1

    # email-templates-website:
    #     container_name: asset-swissgeol-ch-email-templates-website
    #     image: halverneus/static-file-server
    #     restart: unless-stopped
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - ./volumes/email-templates-website:/web
