name: "Container regsistry login & push"
description: "Logins to the registry and pushes the given images"
inputs:
  image:
    description: "Container image name"
    required: true
  username:
    description: "Username for the registry"
    required: true
  password:
    description: "Password for the registry"
    required: true
runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/docker-login
    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push container image
      shell: bash
      run: docker push ${{ inputs.image }}