name: pre-release

on:
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: ghcr.io/geoadmin/swissgeol-assets

jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest
    name: Build and push docker images
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define version
        run: |
          echo VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER >> $GITHUB_ENV          

      - name: Build and push docker image (app)
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ env.BASE_IMAGE_NAME }}-app
          VERSION: ${{ env.VERSION }}
          TAG: rc
          LATEST: false
          DOCKERFILE: ./apps/client-asset-sg/docker/Dockerfile
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image (api)
        uses: ./.github/actions/create-image
        with:
          IMAGE_NAME: ${{ env.BASE_IMAGE_NAME }}-api
          VERSION: ${{ env.VERSION }}
          TAG: rc
          LATEST: false
          DOCKERFILE: ./apps/server-asset-sg/docker/Dockerfile
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Create pre-elease
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body_path: CHANGELOG.md
          commitish: develop
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}