name: Release

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Version (Tag)"
        required: true

env:
  REGISTRY: ghcr.io
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_IMAGE_NAME: ghcr.io/geoadmin/swissgeol-assets

jobs:

  retag-docker-image:
    runs-on: ubuntu-latest
    name: Push updated Docker image

    steps:
      - name: Create Release 
        uses: actions/create-release@v1 
        id: create_release 
        with: 
          draft: false 
          prerelease: false 
          release_name: ${{ env.TAG_NAME }} 
          tag_name: ${{ env.TAG_NAME }} 
          body_path: CHANGELOG.md 
          env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ${{ env.REGISTRY }}
          name: ${{ env.BASE_IMAGE_NAME }}-app
          old_tag: ${{ github.sha }}
          new_tag: latest
          username: github
          password: ${{ secrets.GITHUB_TOKEN }}